[mypy]
# Strict checking for src with flexibility for testing
strict = True
disallow_any_generics = False
warn_return_any = False
no_implicit_optional = True
plugins = sqlalchemy.ext.mypy.plugin

# Relax rules only for tests
[mypy-tests.*]
disallow_untyped_defs = False
check_untyped_defs = True
disallow_untyped_calls = False
disallow_incomplete_defs = False
disallow_any_generics = False
ignore_missing_imports = True
warn_unused_ignores = False 
disable_error_code = attr-defined, annotation-unchecked, untyped-decorator, comparison-overlap
