[tox]
envlist = py{310,311,312,313,314}
isolated_build = True

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314

[coverage:run]
omit =
    tests/*

[testenv]
allowlist_externals = poetry
passenv =
    SCHOLAR_FLUX_*

commands_pre =
    poetry install --with testing --all-extras
commands =
    poetry run pytest {toxinidir}/tests -rx -vv
setenv =
    PYTHONPATH = {toxinidir}/src:{toxinidir}/tests

[testenv:coverage]
allowlist_externals = poetry
deps =
    coverage[toml]
commands_pre =
    poetry install --with testing --all-extras
commands =
    coverage run -m pytest {toxinidir}/tests -rsx -vv
    coverage xml -o {toxinidir}/coverage.xml
    coverage report
setenv =
    PYTHONPATH = {toxinidir}/src:{toxinidir}/tests

[testenv:lint]
allowlist_externals = poetry
commands_pre =
    poetry install --all-extras --with dev
    poetry run mypy --install-types --non-interactive src tests
    poetry run pip install types-requests types-xmltodict types-PyYAML
commands =
    poetry run docstr-coverage src/ --fail-under=100
    poetry run ruff check src tests
    poetry run mypy src tests
